
name = "DashCytoscape"
uuid = "1b08a953-4be3-4667-9a23-b653bd725d15"
authors = ["The Plotly Team <cytoscape@plotly.com>"]
version = "0.1.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compact]
julia = "1.1"
Dash = ">=0.1"
